name: "Test: Code check"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - run: bundle exec rubocop

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - run: bundle exec brakeman -q

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:8.6.2-alpine3.23
        env:
          REDIS_ARGS: "--requirepass redis"
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli -a redis ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME_TEST: shortlink_test
      REDIS_URL: redis://default:redis@localhost:6379/0
      REDIS_POOL_SIZE: 10
      REDIS_POOL_TIMEOUT: 3
      SHORTLINK_SECRET: 03415f6a32e318bc856a1c5612dfaaff
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Setup database
        run: bundle exec rails db:create db:migrate
      - name: Run tests
        run: bundle exec rspec
